[package]
name = "print_name_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
print_name = { path = "../print_name" }
quote = "1.0.20"
syn = "1.0.98"

[lib]
proc-macro = true
